export enum Screen {
  Session = 'Session',
  SessionBook = 'SessionBook',
  Sessions = 'Sessions',
  Tools = 'Tools',
  Note = 'Note',
  NoteAdd = 'NoteAdd',
  OnboardTerms = 'OnboardTerms',
  OnboardPhoto = 'OnboardPhoto',
  OnboardFinish = 'OnboardFinish',
  EditSettings = 'EditSettings',
  Settings = 'Settings',
  camera = 'camera',
  DisciplineTest = 'DisciplineTest',
  EditPossibilities = 'EditPossibilities',
  Focuscheck = 'Focuscheck',
  FocusCheckStart = 'FocusCheckStart',
  FocusCheckStep1 = 'FocusCheckStep1',
  FocusCheckStep2 = 'FocusCheckStep2',
  FocusCheckStep3 = 'FocusCheckStep3',
  FocusCheckStep4 = 'FocusCheckStep4',
  FocusCheckStep5 = 'FocusCheckStep5',
  StatusQuos = 'StatusQuos',
  EditStatusQuo = 'EditStatusQuo',
  Discipline = 'Discipline',
  Disciplines = 'Disciplines',
  Me = 'Me',
  Messages = 'Messages',
  OnboardTrainerStep1 = 'OnboardTrainerStep1',
  OnboardTrainerStep2 = 'OnboardTrainerStep2',
  Terms = 'Terms',
  Trainer = 'Trainer',
  EditVision = 'EditVision',
  Privacy = 'Privacy',
  NavTabs = 'NavTabs',
  Task = 'Task',
  Home = 'Home',
  Journal = 'Journal',
  SignOut = 'SignOut',
  Support = 'Support',
  CancelSubscription = 'CancelSubscription',
  SessionsStack = 'Sessions',
}

export enum AppStartScreen {
  Start = 'Start',
  Auth = 'Auth',
  Support = 'Support',
  Main = 'Main',
}
